version: 1.0.{build}

image:
- Visual Studio 2017

environment:
  matrix:
  - BUILD_TOOLSET: v140
    BUILD_TOOLCHAIN: amd64_x86
  - BUILD_TOOLSET: v140
    BUILD_TOOLCHAIN: amd64
  - BUILD_TOOLSET: v141
    BUILD_TOOLCHAIN: amd64_x86
  - BUILD_TOOLSET: v141
    BUILD_TOOLCHAIN: amd64

install:
- ps: cinst ninja vswhere

build_script:
- cmd: |-
    bash appveyor.sh
